id: P001856
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:26:19.141565
source_metadata:
  id: bdr:W1KG2726
  title: ཀྲུང་གོ་བོད་ཀྱི་རིག་གནས་སྒྱུ་རྩལ་ཀུན་འདུས་ཞལ་ཐང་ཆེན་མོའི་རྣམ་བཤད་མཐོང་གྲོལ་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    c1203cd9d21440bd89893c7723113972:
      image_group_id: I1KG2728
      title: ''
      volume_number: 1
      total_pages: 740
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
