id: opecha:P001856
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG2726
  title: ཀྲུང་གོ་བོད་ཀྱི་རིག་གནས་སྒྱུ་རྩལ་ཀུན་འདུས་ཞལ་ཐང་ཆེན་མོའི་རྣམ་བཤད་མཐོང་གྲོལ་ཀུན་གསལ་མེ་ལོང་།
  volume: ''
  author: ''
