id: IFB1AACEE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T16:01:17+00:00'
last_modified: '2022-06-07T15:24:06.441933+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG2726
  title: ཀྲུང་གོ་བོད་ཀྱི་རིག་གནས་སྒྱུ་རྩལ་ཀུན་འདུས་ཞལ་ཐང་ཆེན་མོའི་རྣམ་བཤད་མཐོང་གྲོལ་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '8149':
      image_group_id: I1KG2728
      title: ''
      total_pages: 740
      order: 1
      base_file: 8149.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
